version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fxql_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: fxql_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fxql_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: