services:
  - type: web
    name: fxql-backend
    env: node
    region: ohio  # or your preferred region
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RATE_LIMIT_MAX
        value: 50
      - key: CORS_ENABLED
        value: true
      - key: CORS_ORIGIN
        value: "*"  # Update this with your frontend domain
      - key: DATABASE_URL
        fromDatabase:
          name: fxql-db
          property: connectionString

databases:
  - name: fxql-backend
    region: ohio  # or your preferred region
    plan: starter