services:
  - type: web
    name: fxql-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fxql-db
          property: connectionString

databases:
  - name: fxql-db
    plan: starter