services:
  - type: web
    name: fxql-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    # Add build optimization
    buildFilter:
      paths:
        - src/**/*.ts
        - package.json
        - package-lock.json
        - tsconfig.json
    # Add automatic scaling
    autoscaling:
      enabled: true
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RATE_LIMIT_MAX
        value: 50
      - key: CORS_ENABLED
        value: true
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: fxql-backend
          property: connectionString
    # Add resource allocation
    resourceAllocation:
      cpu: 1x
      memory: 512MB